"""
Django settings for count_admin_project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['']


# Application definition

INSTALLED_APPS = [
    "phonenumber_field",
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks', #pip install django-widget-tweaks
    'django.contrib.humanize',
    'axes',
    'count',
    'user',
    'custom_admin.apps.CustomAdminConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.OneSessionPerUserMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'count_admin_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.views.context_app',  # seagrego variable de contexto server de plex a esta function
            ],
        },
    },
]

WSGI_APPLICATION = 'count_admin_project.wsgi.application'



AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': '',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-CO'
TIME_ZONE = 'America/Bogota'


USE_I18N = True
OPT_ACTIVE = False
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

LOGOS_URL = '/logos/'
# Path where media is stored
LOGOS_ROOT = os.path.join(BASE_DIR, 'logos/')

PROMOTIONS_URL = '/promotions/'
PROMOTIONS_ROOT = os.path.join(BASE_DIR, 'promotions/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
if OPT_ACTIVE:

    LOGIN_URL = '/user/login'
    LOGIN_REDIRECT_URL = '/user/'
    LOGOUT_REDIRECT_URL = '/user/login'
else:

    LOGIN_URL = '/user/accounts/login'
    LOGIN_REDIRECT_URL = '/user/'
    LOGOUT_REDIRECT_URL = '/user/accounts/login'

# API de whatsapp
TOKEN_WHATSAPP_API = ""
INSTANCE_WHATSAPP_API = ""

TITLES_INTER_DATES = {
    'sales': {
        'model': 'sales',
        'title': 'Ventas',
        'lead': 'Tu listado de ventas',
        'message': 'Selecciona la fecha a filtrar'
    }
}
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600 # 600 por defecto
SESSION_SAVE_EVERY_REQUEST = True
AXES_LOGIN_FAILURE_LIMIT = 1
AXES_COOLOFF_TIME = 0.1 # tiempo de espera para volver a intentar loguin en horas
AXES_LOCKOUT_TEMPLATE = 'lockscreen.html'
